### ISSUE TITLE
layout not defined

### ISSUE THREAD

**Issue by olivierlfranck** [JacksonTian/ejs-mate#29]
i'm getting this error
ReferenceError: C:\Users\OLYNSEC\ecommerce\views\home.ejs:1
 >> 1| <% Layout('boilerplate') -%>

    2| 

    3| 

    4| <h1> shop smart, save big!</h1>

Layouts is not defined
    at eval (eval at compile (C:\Users\OLYNSEC\ecommerce\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:9:8)
    at returnedFn (C:\Users\OLYNSEC\ecommerce\node_modules\ejs\lib\ejs.js:580:17)
    at tryHandleCache (C:\Users\OLYNSEC\ecommerce\node_modules\ejs\lib\ejs.js:223:34)
    at View.exports.renderFile [as engine] (C:\Users\OLYNSEC\ecommerce\node_modules\ejs\lib\ejs.js:437:10)
    at View.render (C:\Users\OLYNSEC\ecommerce\node_modules\express\lib\view.js:127:8)
    at tryRender (C:\Users\OLYNSEC\ecommerce\node_modules\express\lib\application.js:640:10)
    at EventEmitter.render (C:\Users\OLYNSEC\ecommerce\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\OLYNSEC\ecommerce\node_modules\express\lib\response.js:971:7)
    at C:\Users\OLYNSEC\ecommerce\server.js:46:7
    at Layer.handle [as handle_request] (C:\Users\OLYNSEC\ecommerce\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\OLYNSEC\ecommerce\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\OLYNSEC\ecommerce\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\OLYNSEC\ecommerce\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\OLYNSEC\ecommerce\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\OLYNSEC\ecommerce\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\OLYNSEC\ecommerce\node_modules\express\lib\router\index.js:275:10)
 

can someone help me using latest version of nodejs thank you ahead

**Comment by JacksonTian** [comment]
please use lowercase "layout"

**Comment by olivierlfranck** [comment]
i used lowercase "layout" this isthe configuration of my home.ejs file
<% layout('boilerplate') -%>


<h1> shop smart, save big!</h1>
<p>starting point to create something more unique</p>

<p>Signup to start buying</p>
<h3>start your search here</h3>

<p>our prices are some of the best on the web</p>
<h3>look for smart item</h3>
<p>this will appearr across the site as add to your cart</p>
<h3>build a smart cart</h3>

<p>the more smart</p>
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
this is my boilerplate.ejs file
<!DOCTYPE html>
<head>
  <title>hello world</title>
</head>

<body>

  <h1>this is a boilerplate page</h1>


  <%- body -%>


</body>

</html>
//////////////////////////////////////////////////////////////////////////////////////
thanks to help me ahead

**Comment by coolaj86** [comment]
Remove the `.txt` extension.
